version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels: ["type:deps", "tier-1"]
    commit-message:
      prefix: "ci"
      include: "scope"
