# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by scripts/gen-windows-plugin-shim.py — do not edit.
#
# The host ABI symbols a plugin resolves against the loading
# executable. On ELF, -rdynamic publishes them all and no list is
# needed. MSVC exports only what is asked for, and
# WINDOWS_EXPORT_ALL_SYMBOLS did not apply to these executables, so
# every host shipped with an empty export table and every plugin
# loaded and registered nothing.
#
# Naming them explicitly also makes the export set exactly the ABI —
# not every global symbol that happens to be in the binary — and it
# comes from the same generator as the plugin-side shim, so the two
# cannot drift.

set(SOUXMAR_HOST_ABI_SYMBOLS
  souxmar_brep_body_bounds
  souxmar_brep_body_id
  souxmar_brep_body_name
  souxmar_brep_boolean
  souxmar_brep_chamfer
  souxmar_brep_delete_body
  souxmar_brep_extrude
  souxmar_brep_fillet
  souxmar_brep_import_iges
  souxmar_brep_import_step
  souxmar_brep_loft
  souxmar_brep_num_bodies
  souxmar_brep_pattern_circular
  souxmar_brep_pattern_linear
  souxmar_brep_revolve
  souxmar_brep_session_close
  souxmar_brep_session_open
  souxmar_brep_sweep
  souxmar_brep_tessellate
  souxmar_brep_to_geometry
  souxmar_buffer_alignment
  souxmar_buffer_data
  souxmar_buffer_data_const
  souxmar_buffer_free
  souxmar_buffer_is_mmap
  souxmar_buffer_new
  souxmar_buffer_new_mmap
  souxmar_buffer_size
  souxmar_field_components
  souxmar_field_count
  souxmar_field_data
  souxmar_field_data_const
  souxmar_field_data_size
  souxmar_field_free
  souxmar_field_kind
  souxmar_field_location
  souxmar_field_name
  souxmar_field_new
  souxmar_field_num_time_steps
  souxmar_field_stream_close
  souxmar_field_stream_components
  souxmar_field_stream_count
  souxmar_field_stream_open
  souxmar_field_stream_range
  souxmar_field_stream_units
  souxmar_field_stream_values
  souxmar_geometry_add_edge
  souxmar_geometry_add_face
  souxmar_geometry_add_solid
  souxmar_geometry_add_vertex
  souxmar_geometry_bounding_box
  souxmar_geometry_count
  souxmar_geometry_free
  souxmar_geometry_name
  souxmar_geometry_new
  souxmar_geometry_num_edges
  souxmar_geometry_num_faces
  souxmar_geometry_num_solids
  souxmar_geometry_num_vertices
  souxmar_geometry_set_name
  souxmar_geometry_set_tag
  souxmar_geometry_tag
  souxmar_geometry_vertex_position
  souxmar_mesh_add_cell
  souxmar_mesh_add_node
  souxmar_mesh_cell_face_count
  souxmar_mesh_cell_node_count
  souxmar_mesh_cell_nodes
  souxmar_mesh_cell_tag
  souxmar_mesh_cell_type
  souxmar_mesh_face_tag
  souxmar_mesh_free
  souxmar_mesh_from_buffers
  souxmar_mesh_new
  souxmar_mesh_node
  souxmar_mesh_nodes_flat
  souxmar_mesh_num_cells
  souxmar_mesh_num_nodes
  souxmar_mesh_reserve_cells
  souxmar_mesh_reserve_nodes
  souxmar_mesh_set_face_tag
  souxmar_registry_add_mesher
  souxmar_registry_add_postproc
  souxmar_registry_add_reader
  souxmar_registry_add_solver
  souxmar_registry_add_writer
  souxmar_sketch_add_arc
  souxmar_sketch_add_circle
  souxmar_sketch_add_constraint
  souxmar_sketch_add_line
  souxmar_sketch_add_point
  souxmar_sketch_anchor_face
  souxmar_sketch_anchor_world
  souxmar_sketch_free
  souxmar_sketch_new
  souxmar_sketch_num_constraints
  souxmar_sketch_num_primitives
  souxmar_sketch_point_position
  souxmar_sketch_solve
  souxmar_surface_stream_bounds
  souxmar_surface_stream_close
  souxmar_surface_stream_face_ids
  souxmar_surface_stream_indices
  souxmar_surface_stream_normals
  souxmar_surface_stream_open
  souxmar_surface_stream_positions
  souxmar_surface_stream_triangle_count
  souxmar_surface_stream_vertex_count
  souxmar_surface_stream_vertex_ids
  souxmar_timeseries_cache_preload
  souxmar_timeseries_cache_window
  souxmar_timeseries_close
  souxmar_timeseries_field_count
  souxmar_timeseries_field_name
  souxmar_timeseries_frame
  souxmar_timeseries_frame_count
  souxmar_timeseries_open
  souxmar_timeseries_time
  souxmar_value_as_bool
  souxmar_value_as_number
  souxmar_value_as_stage
  souxmar_value_as_string
  souxmar_value_kind
  souxmar_value_list_at
  souxmar_value_list_size
  souxmar_value_map_get
  souxmar_value_map_size
)

