/* SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/gen-windows-plugin-shim.py — do not edit.
 * Regenerate after any change to include/souxmar-c/**; CI checks it.
 *
 * Windows-only. Every souxmar host ABI function gets a thunk that
 * resolves itself on first call against the running executable, which
 * is what ELF and Mach-O do for a dlopen()ed plugin automatically and
 * what a Windows DLL cannot express in its import table.
 *
 * A plugin links this statically. It is not part of the ABI: the symbol
 * names, signatures and semantics are exactly those of souxmar-c/**.
 */

#if defined(_WIN32)

#include <windows.h>
#include <stddef.h>
#include <string.h>

#include "souxmar-c/abi.h"
#include "souxmar-c/brep.h"
#include "souxmar-c/buffer.h"
#include "souxmar-c/field.h"
#include "souxmar-c/field_stream.h"
#include "souxmar-c/geometry.h"
#include "souxmar-c/mesh.h"
#include "souxmar-c/mesher.h"
#include "souxmar-c/plugin.h"
#include "souxmar-c/postproc.h"
#include "souxmar-c/reader.h"
#include "souxmar-c/registry.h"
#include "souxmar-c/sketch.h"
#include "souxmar-c/solver.h"
#include "souxmar-c/status.h"
#include "souxmar-c/surface_stream.h"
#include "souxmar-c/timeseries.h"
#include "souxmar-c/types.h"
#include "souxmar-c/value.h"
#include "souxmar-c/writer.h"

/* Resolve against the executable that loaded this plugin. Hosts are
 * built with CMAKE_EXECUTABLE_ENABLE_EXPORTS, so the symbols are in
 * the EXE's export table. A miss means the loader is not a souxmar
 * host, which is a caller error, not something a plugin can recover
 * from — the thunk returns a zeroed value rather than jumping to
 * NULL, so the failure is a diagnosable bad result and not a crash
 * inside the plugin. */
static FARPROC souxmar_shim_lookup(const char* name) {
  static HMODULE host = NULL;
  if (host == NULL) {
    host = GetModuleHandleW(NULL);
  }
  return host ? GetProcAddress(host, name) : NULL;
}

souxmar_status_t souxmar_brep_body_bounds(const souxmar_brep_session_t* session, uint64_t body_id, double out_min[3], double out_max[3]) {
  typedef souxmar_status_t (*fn_t)(const souxmar_brep_session_t* session, uint64_t body_id, double out_min[3], double out_max[3]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_body_bounds");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_body_bounds";
    return err;
  }
  return fn(session, body_id, out_min, out_max);
}

souxmar_status_t souxmar_brep_body_id(const souxmar_brep_session_t* session, size_t index, uint64_t* out_body_id) {
  typedef souxmar_status_t (*fn_t)(const souxmar_brep_session_t* session, size_t index, uint64_t* out_body_id);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_body_id");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_body_id";
    return err;
  }
  return fn(session, index, out_body_id);
}

const char* souxmar_brep_body_name(const souxmar_brep_session_t* session, uint64_t body_id) {
  typedef const char* (*fn_t)(const souxmar_brep_session_t* session, uint64_t body_id);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_body_name");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session, body_id);
}

souxmar_status_t souxmar_brep_boolean(souxmar_brep_session_t* session, uint64_t target_body_id, uint64_t tool_body_id, uint8_t operation) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, uint64_t target_body_id, uint64_t tool_body_id, uint8_t operation);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_boolean");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_boolean";
    return err;
  }
  return fn(session, target_body_id, tool_body_id, operation);
}

souxmar_status_t souxmar_brep_chamfer(souxmar_brep_session_t* session, uint64_t body_id, const uint64_t* edge_ids, size_t edge_count, double distance) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, uint64_t body_id, const uint64_t* edge_ids, size_t edge_count, double distance);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_chamfer");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_chamfer";
    return err;
  }
  return fn(session, body_id, edge_ids, edge_count, distance);
}

souxmar_status_t souxmar_brep_delete_body(souxmar_brep_session_t* session, uint64_t body_id) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, uint64_t body_id);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_delete_body");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_delete_body";
    return err;
  }
  return fn(session, body_id);
}

uint64_t souxmar_brep_extrude(souxmar_brep_session_t* session, const struct souxmar_sketch_t* sketch, double distance, uint8_t direction, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status) {
  typedef uint64_t (*fn_t)(souxmar_brep_session_t* session, const struct souxmar_sketch_t* sketch, double distance, uint8_t direction, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_extrude");
  }
  if (!fn) { uint64_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session, sketch, distance, direction, operation, target_body_id, out_status);
}

souxmar_status_t souxmar_brep_fillet(souxmar_brep_session_t* session, uint64_t body_id, const uint64_t* edge_ids, size_t edge_count, double radius) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, uint64_t body_id, const uint64_t* edge_ids, size_t edge_count, double radius);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_fillet");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_fillet";
    return err;
  }
  return fn(session, body_id, edge_ids, edge_count, radius);
}

souxmar_status_t souxmar_brep_import_iges(souxmar_brep_session_t* session, const char* path) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, const char* path);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_import_iges");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_import_iges";
    return err;
  }
  return fn(session, path);
}

souxmar_status_t souxmar_brep_import_step(souxmar_brep_session_t* session, const char* path) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, const char* path);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_import_step");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_import_step";
    return err;
  }
  return fn(session, path);
}

uint64_t souxmar_brep_loft(souxmar_brep_session_t* session, const struct souxmar_sketch_t** profiles, size_t profile_count, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status) {
  typedef uint64_t (*fn_t)(souxmar_brep_session_t* session, const struct souxmar_sketch_t** profiles, size_t profile_count, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_loft");
  }
  if (!fn) { uint64_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session, profiles, profile_count, operation, target_body_id, out_status);
}

size_t souxmar_brep_num_bodies(const souxmar_brep_session_t* session) {
  typedef size_t (*fn_t)(const souxmar_brep_session_t* session);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_num_bodies");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session);
}

souxmar_status_t souxmar_brep_pattern_circular(souxmar_brep_session_t* session, const uint64_t* source_body_ids, size_t source_count, const double axis_origin[3], const double axis_direction[3], double angle_rad, uint32_t count) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, const uint64_t* source_body_ids, size_t source_count, const double axis_origin[3], const double axis_direction[3], double angle_rad, uint32_t count);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_pattern_circular");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_pattern_circular";
    return err;
  }
  return fn(session, source_body_ids, source_count, axis_origin, axis_direction, angle_rad, count);
}

souxmar_status_t souxmar_brep_pattern_linear(souxmar_brep_session_t* session, const uint64_t* source_body_ids, size_t source_count, const double direction[3], double spacing, uint32_t count) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, const uint64_t* source_body_ids, size_t source_count, const double direction[3], double spacing, uint32_t count);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_pattern_linear");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_pattern_linear";
    return err;
  }
  return fn(session, source_body_ids, source_count, direction, spacing, count);
}

uint64_t souxmar_brep_revolve(souxmar_brep_session_t* session, const struct souxmar_sketch_t* sketch, uint32_t axis_line_id, double angle_rad, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status) {
  typedef uint64_t (*fn_t)(souxmar_brep_session_t* session, const struct souxmar_sketch_t* sketch, uint32_t axis_line_id, double angle_rad, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_revolve");
  }
  if (!fn) { uint64_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session, sketch, axis_line_id, angle_rad, operation, target_body_id, out_status);
}

void souxmar_brep_session_close(souxmar_brep_session_t* session) {
  typedef void (*fn_t)(souxmar_brep_session_t* session);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_session_close");
  }
  if (fn) fn(session);
}

souxmar_brep_session_t* souxmar_brep_session_open(void) {
  typedef souxmar_brep_session_t* (*fn_t)(void);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_session_open");
  }
  if (!fn) { souxmar_brep_session_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn();
}

uint64_t souxmar_brep_sweep(souxmar_brep_session_t* session, const struct souxmar_sketch_t* profile, const struct souxmar_sketch_t* path, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status) {
  typedef uint64_t (*fn_t)(souxmar_brep_session_t* session, const struct souxmar_sketch_t* profile, const struct souxmar_sketch_t* path, uint8_t operation, uint64_t target_body_id, souxmar_status_t* out_status);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_sweep");
  }
  if (!fn) { uint64_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session, profile, path, operation, target_body_id, out_status);
}

souxmar_status_t souxmar_brep_tessellate(souxmar_brep_session_t* session, uint64_t body_id, double deflection, souxmar_mesh_t** out_surface_mesh) {
  typedef souxmar_status_t (*fn_t)(souxmar_brep_session_t* session, uint64_t body_id, double deflection, souxmar_mesh_t** out_surface_mesh);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_tessellate");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_brep_tessellate";
    return err;
  }
  return fn(session, body_id, deflection, out_surface_mesh);
}

souxmar_geometry_t* souxmar_brep_to_geometry(const souxmar_brep_session_t* session) {
  typedef souxmar_geometry_t* (*fn_t)(const souxmar_brep_session_t* session);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_brep_to_geometry");
  }
  if (!fn) { souxmar_geometry_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(session);
}

size_t souxmar_buffer_alignment(void) {
  typedef size_t (*fn_t)(void);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_alignment");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn();
}

void* souxmar_buffer_data(souxmar_buffer_t* buffer) {
  typedef void* (*fn_t)(souxmar_buffer_t* buffer);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_data");
  }
  if (!fn) { void* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(buffer);
}

const void* souxmar_buffer_data_const(const souxmar_buffer_t* buffer) {
  typedef const void* (*fn_t)(const souxmar_buffer_t* buffer);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_data_const");
  }
  if (!fn) { const void* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(buffer);
}

void souxmar_buffer_free(souxmar_buffer_t* buffer) {
  typedef void (*fn_t)(souxmar_buffer_t* buffer);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_free");
  }
  if (fn) fn(buffer);
}

int souxmar_buffer_is_mmap(const souxmar_buffer_t* buffer) {
  typedef int (*fn_t)(const souxmar_buffer_t* buffer);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_is_mmap");
  }
  if (!fn) { int zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(buffer);
}

souxmar_buffer_t* souxmar_buffer_new(size_t size_bytes) {
  typedef souxmar_buffer_t* (*fn_t)(size_t size_bytes);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_new");
  }
  if (!fn) { souxmar_buffer_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(size_bytes);
}

souxmar_buffer_t* souxmar_buffer_new_mmap(const char* path, size_t size_bytes, uint32_t flags) {
  typedef souxmar_buffer_t* (*fn_t)(const char* path, size_t size_bytes, uint32_t flags);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_new_mmap");
  }
  if (!fn) { souxmar_buffer_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(path, size_bytes, flags);
}

size_t souxmar_buffer_size(const souxmar_buffer_t* buffer) {
  typedef size_t (*fn_t)(const souxmar_buffer_t* buffer);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_buffer_size");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(buffer);
}

uint8_t souxmar_field_components(const souxmar_field_t* field) {
  typedef uint8_t (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_components");
  }
  if (!fn) { uint8_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

size_t souxmar_field_count(const souxmar_field_t* field) {
  typedef size_t (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

double* souxmar_field_data(souxmar_field_t* field) {
  typedef double* (*fn_t)(souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_data");
  }
  if (!fn) { double* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

const double* souxmar_field_data_const(const souxmar_field_t* field) {
  typedef const double* (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_data_const");
  }
  if (!fn) { const double* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

size_t souxmar_field_data_size(const souxmar_field_t* field) {
  typedef size_t (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_data_size");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

void souxmar_field_free(souxmar_field_t* field) {
  typedef void (*fn_t)(souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_free");
  }
  if (fn) fn(field);
}

uint8_t souxmar_field_kind(const souxmar_field_t* field) {
  typedef uint8_t (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_kind");
  }
  if (!fn) { uint8_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

uint8_t souxmar_field_location(const souxmar_field_t* field) {
  typedef uint8_t (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_location");
  }
  if (!fn) { uint8_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

const char* souxmar_field_name(const souxmar_field_t* field) {
  typedef const char* (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_name");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

souxmar_field_t* souxmar_field_new(const char* name, uint8_t location, uint8_t kind, size_t count, size_t num_time_steps) {
  typedef souxmar_field_t* (*fn_t)(const char* name, uint8_t location, uint8_t kind, size_t count, size_t num_time_steps);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_new");
  }
  if (!fn) { souxmar_field_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(name, location, kind, count, num_time_steps);
}

size_t souxmar_field_num_time_steps(const souxmar_field_t* field) {
  typedef size_t (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_num_time_steps");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

void souxmar_field_stream_close(souxmar_field_stream_t* stream) {
  typedef void (*fn_t)(souxmar_field_stream_t* stream);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_close");
  }
  if (fn) fn(stream);
}

uint8_t souxmar_field_stream_components(const souxmar_field_stream_t* s) {
  typedef uint8_t (*fn_t)(const souxmar_field_stream_t* s);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_components");
  }
  if (!fn) { uint8_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(s);
}

size_t souxmar_field_stream_count(const souxmar_field_stream_t* s) {
  typedef size_t (*fn_t)(const souxmar_field_stream_t* s);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(s);
}

souxmar_field_stream_t* souxmar_field_stream_open(const souxmar_field_t* field) {
  typedef souxmar_field_stream_t* (*fn_t)(const souxmar_field_t* field);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_open");
  }
  if (!fn) { souxmar_field_stream_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(field);
}

souxmar_status_t souxmar_field_stream_range(const souxmar_field_stream_t* s, double* out_min, double* out_max) {
  typedef souxmar_status_t (*fn_t)(const souxmar_field_stream_t* s, double* out_min, double* out_max);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_range");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_field_stream_range";
    return err;
  }
  return fn(s, out_min, out_max);
}

const char* souxmar_field_stream_units(const souxmar_field_stream_t* s) {
  typedef const char* (*fn_t)(const souxmar_field_stream_t* s);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_units");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(s);
}

souxmar_status_t souxmar_field_stream_values(const souxmar_field_stream_t* s, float* out, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_field_stream_t* s, float* out, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_field_stream_values");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_field_stream_values";
    return err;
  }
  return fn(s, out, out_capacity);
}

uint32_t souxmar_geometry_add_edge(souxmar_geometry_t* g) {
  typedef uint32_t (*fn_t)(souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_add_edge");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

uint32_t souxmar_geometry_add_face(souxmar_geometry_t* g) {
  typedef uint32_t (*fn_t)(souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_add_face");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

uint32_t souxmar_geometry_add_solid(souxmar_geometry_t* g) {
  typedef uint32_t (*fn_t)(souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_add_solid");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

uint32_t souxmar_geometry_add_vertex(souxmar_geometry_t* g, const double position[3]) {
  typedef uint32_t (*fn_t)(souxmar_geometry_t* g, const double position[3]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_add_vertex");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g, position);
}

souxmar_status_t souxmar_geometry_bounding_box(const souxmar_geometry_t* g, double out_box[6]) {
  typedef souxmar_status_t (*fn_t)(const souxmar_geometry_t* g, double out_box[6]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_bounding_box");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_geometry_bounding_box";
    return err;
  }
  return fn(g, out_box);
}

size_t souxmar_geometry_count(const souxmar_geometry_t* g, uint8_t kind) {
  typedef size_t (*fn_t)(const souxmar_geometry_t* g, uint8_t kind);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g, kind);
}

void souxmar_geometry_free(souxmar_geometry_t* geometry) {
  typedef void (*fn_t)(souxmar_geometry_t* geometry);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_free");
  }
  if (fn) fn(geometry);
}

const char* souxmar_geometry_name(const souxmar_geometry_t* g, uint8_t kind, uint32_t index) {
  typedef const char* (*fn_t)(const souxmar_geometry_t* g, uint8_t kind, uint32_t index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_name");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g, kind, index);
}

souxmar_geometry_t* souxmar_geometry_new(void) {
  typedef souxmar_geometry_t* (*fn_t)(void);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_new");
  }
  if (!fn) { souxmar_geometry_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn();
}

size_t souxmar_geometry_num_edges(const souxmar_geometry_t* g) {
  typedef size_t (*fn_t)(const souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_num_edges");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

size_t souxmar_geometry_num_faces(const souxmar_geometry_t* g) {
  typedef size_t (*fn_t)(const souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_num_faces");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

size_t souxmar_geometry_num_solids(const souxmar_geometry_t* g) {
  typedef size_t (*fn_t)(const souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_num_solids");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

size_t souxmar_geometry_num_vertices(const souxmar_geometry_t* g) {
  typedef size_t (*fn_t)(const souxmar_geometry_t* g);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_num_vertices");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g);
}

souxmar_status_t souxmar_geometry_set_name(souxmar_geometry_t* g, uint8_t kind, uint32_t index, const char* name) {
  typedef souxmar_status_t (*fn_t)(souxmar_geometry_t* g, uint8_t kind, uint32_t index, const char* name);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_set_name");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_geometry_set_name";
    return err;
  }
  return fn(g, kind, index, name);
}

souxmar_status_t souxmar_geometry_set_tag(souxmar_geometry_t* g, uint8_t kind, uint32_t index, int32_t tag) {
  typedef souxmar_status_t (*fn_t)(souxmar_geometry_t* g, uint8_t kind, uint32_t index, int32_t tag);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_set_tag");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_geometry_set_tag";
    return err;
  }
  return fn(g, kind, index, tag);
}

int32_t souxmar_geometry_tag(const souxmar_geometry_t* g, uint8_t kind, uint32_t index) {
  typedef int32_t (*fn_t)(const souxmar_geometry_t* g, uint8_t kind, uint32_t index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_tag");
  }
  if (!fn) { int32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(g, kind, index);
}

souxmar_status_t souxmar_geometry_vertex_position(const souxmar_geometry_t* g, uint32_t vertex_index, double out_position[3]) {
  typedef souxmar_status_t (*fn_t)(const souxmar_geometry_t* g, uint32_t vertex_index, double out_position[3]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_geometry_vertex_position");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_geometry_vertex_position";
    return err;
  }
  return fn(g, vertex_index, out_position);
}

souxmar_status_t souxmar_mesh_add_cell(souxmar_mesh_t* mesh, uint16_t element_type, const uint64_t* node_indices, size_t num_node_indices, int32_t tag, uint64_t* out_cell_index) {
  typedef souxmar_status_t (*fn_t)(souxmar_mesh_t* mesh, uint16_t element_type, const uint64_t* node_indices, size_t num_node_indices, int32_t tag, uint64_t* out_cell_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_add_cell");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_mesh_add_cell";
    return err;
  }
  return fn(mesh, element_type, node_indices, num_node_indices, tag, out_cell_index);
}

uint64_t souxmar_mesh_add_node(souxmar_mesh_t* mesh, const double position[3]) {
  typedef uint64_t (*fn_t)(souxmar_mesh_t* mesh, const double position[3]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_add_node");
  }
  if (!fn) { uint64_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, position);
}

size_t souxmar_mesh_cell_face_count(const souxmar_mesh_t* mesh, uint64_t cell_index) {
  typedef size_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t cell_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_cell_face_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, cell_index);
}

size_t souxmar_mesh_cell_node_count(const souxmar_mesh_t* mesh, uint64_t cell_index) {
  typedef size_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t cell_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_cell_node_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, cell_index);
}

souxmar_status_t souxmar_mesh_cell_nodes(const souxmar_mesh_t* mesh, uint64_t cell_index, uint64_t* out_node_indices, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t cell_index, uint64_t* out_node_indices, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_cell_nodes");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_mesh_cell_nodes";
    return err;
  }
  return fn(mesh, cell_index, out_node_indices, out_capacity);
}

int32_t souxmar_mesh_cell_tag(const souxmar_mesh_t* mesh, uint64_t cell_index) {
  typedef int32_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t cell_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_cell_tag");
  }
  if (!fn) { int32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, cell_index);
}

uint16_t souxmar_mesh_cell_type(const souxmar_mesh_t* mesh, uint64_t cell_index) {
  typedef uint16_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t cell_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_cell_type");
  }
  if (!fn) { uint16_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, cell_index);
}

int32_t souxmar_mesh_face_tag(const souxmar_mesh_t* mesh, uint64_t cell_index, uint8_t local_face_index) {
  typedef int32_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t cell_index, uint8_t local_face_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_face_tag");
  }
  if (!fn) { int32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, cell_index, local_face_index);
}

void souxmar_mesh_free(souxmar_mesh_t* mesh) {
  typedef void (*fn_t)(souxmar_mesh_t* mesh);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_free");
  }
  if (fn) fn(mesh);
}

souxmar_mesh_t* souxmar_mesh_from_buffers(const souxmar_mesh_buffers_t* buffers, souxmar_status_t* out_status) {
  typedef souxmar_mesh_t* (*fn_t)(const souxmar_mesh_buffers_t* buffers, souxmar_status_t* out_status);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_from_buffers");
  }
  if (!fn) { souxmar_mesh_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(buffers, out_status);
}

souxmar_mesh_t* souxmar_mesh_new(void) {
  typedef souxmar_mesh_t* (*fn_t)(void);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_new");
  }
  if (!fn) { souxmar_mesh_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn();
}

souxmar_status_t souxmar_mesh_node(const souxmar_mesh_t* mesh, uint64_t index, double out_position[3]) {
  typedef souxmar_status_t (*fn_t)(const souxmar_mesh_t* mesh, uint64_t index, double out_position[3]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_node");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_mesh_node";
    return err;
  }
  return fn(mesh, index, out_position);
}

const double* souxmar_mesh_nodes_flat(const souxmar_mesh_t* mesh, size_t* out_size) {
  typedef const double* (*fn_t)(const souxmar_mesh_t* mesh, size_t* out_size);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_nodes_flat");
  }
  if (!fn) { const double* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh, out_size);
}

size_t souxmar_mesh_num_cells(const souxmar_mesh_t* mesh) {
  typedef size_t (*fn_t)(const souxmar_mesh_t* mesh);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_num_cells");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh);
}

size_t souxmar_mesh_num_nodes(const souxmar_mesh_t* mesh) {
  typedef size_t (*fn_t)(const souxmar_mesh_t* mesh);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_num_nodes");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh);
}

void souxmar_mesh_reserve_cells(souxmar_mesh_t* mesh, size_t n) {
  typedef void (*fn_t)(souxmar_mesh_t* mesh, size_t n);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_reserve_cells");
  }
  if (fn) fn(mesh, n);
}

void souxmar_mesh_reserve_nodes(souxmar_mesh_t* mesh, size_t n) {
  typedef void (*fn_t)(souxmar_mesh_t* mesh, size_t n);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_reserve_nodes");
  }
  if (fn) fn(mesh, n);
}

souxmar_status_t souxmar_mesh_set_face_tag(souxmar_mesh_t* mesh, uint64_t cell_index, uint8_t local_face_index, int32_t tag) {
  typedef souxmar_status_t (*fn_t)(souxmar_mesh_t* mesh, uint64_t cell_index, uint8_t local_face_index, int32_t tag);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_mesh_set_face_tag");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_mesh_set_face_tag";
    return err;
  }
  return fn(mesh, cell_index, local_face_index, tag);
}

souxmar_status_t souxmar_registry_add_mesher(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_mesher_vtable* vtable, void* user_data) {
  typedef souxmar_status_t (*fn_t)(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_mesher_vtable* vtable, void* user_data);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_registry_add_mesher");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_registry_add_mesher";
    return err;
  }
  return fn(registry, capability_id, vtable, user_data);
}

souxmar_status_t souxmar_registry_add_postproc(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_postproc_vtable* vtable, void* user_data) {
  typedef souxmar_status_t (*fn_t)(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_postproc_vtable* vtable, void* user_data);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_registry_add_postproc");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_registry_add_postproc";
    return err;
  }
  return fn(registry, capability_id, vtable, user_data);
}

souxmar_status_t souxmar_registry_add_reader(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_reader_vtable* vtable, void* user_data) {
  typedef souxmar_status_t (*fn_t)(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_reader_vtable* vtable, void* user_data);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_registry_add_reader");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_registry_add_reader";
    return err;
  }
  return fn(registry, capability_id, vtable, user_data);
}

souxmar_status_t souxmar_registry_add_solver(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_solver_vtable* vtable, void* user_data) {
  typedef souxmar_status_t (*fn_t)(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_solver_vtable* vtable, void* user_data);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_registry_add_solver");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_registry_add_solver";
    return err;
  }
  return fn(registry, capability_id, vtable, user_data);
}

souxmar_status_t souxmar_registry_add_writer(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_writer_vtable* vtable, void* user_data) {
  typedef souxmar_status_t (*fn_t)(souxmar_registry_t* registry, const char* capability_id, const struct souxmar_writer_vtable* vtable, void* user_data);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_registry_add_writer");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_registry_add_writer";
    return err;
  }
  return fn(registry, capability_id, vtable, user_data);
}

uint32_t souxmar_sketch_add_arc(souxmar_sketch_t* sketch, uint32_t start_point_id, uint32_t end_point_id, uint32_t centre_point_id) {
  typedef uint32_t (*fn_t)(souxmar_sketch_t* sketch, uint32_t start_point_id, uint32_t end_point_id, uint32_t centre_point_id);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_add_arc");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch, start_point_id, end_point_id, centre_point_id);
}

uint32_t souxmar_sketch_add_circle(souxmar_sketch_t* sketch, uint32_t centre_point_id, double radius) {
  typedef uint32_t (*fn_t)(souxmar_sketch_t* sketch, uint32_t centre_point_id, double radius);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_add_circle");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch, centre_point_id, radius);
}

uint32_t souxmar_sketch_add_constraint(souxmar_sketch_t* sketch, uint8_t kind, const uint32_t* targets, size_t target_count, double value) {
  typedef uint32_t (*fn_t)(souxmar_sketch_t* sketch, uint8_t kind, const uint32_t* targets, size_t target_count, double value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_add_constraint");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch, kind, targets, target_count, value);
}

uint32_t souxmar_sketch_add_line(souxmar_sketch_t* sketch, uint32_t start_point_id, uint32_t end_point_id) {
  typedef uint32_t (*fn_t)(souxmar_sketch_t* sketch, uint32_t start_point_id, uint32_t end_point_id);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_add_line");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch, start_point_id, end_point_id);
}

uint32_t souxmar_sketch_add_point(souxmar_sketch_t* sketch, double u, double v) {
  typedef uint32_t (*fn_t)(souxmar_sketch_t* sketch, double u, double v);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_add_point");
  }
  if (!fn) { uint32_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch, u, v);
}

souxmar_status_t souxmar_sketch_anchor_face(souxmar_sketch_t* sketch, const souxmar_brep_session_t* session, uint64_t face_id) {
  typedef souxmar_status_t (*fn_t)(souxmar_sketch_t* sketch, const souxmar_brep_session_t* session, uint64_t face_id);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_anchor_face");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_sketch_anchor_face";
    return err;
  }
  return fn(sketch, session, face_id);
}

souxmar_status_t souxmar_sketch_anchor_world(souxmar_sketch_t* sketch, uint8_t plane) {
  typedef souxmar_status_t (*fn_t)(souxmar_sketch_t* sketch, uint8_t plane);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_anchor_world");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_sketch_anchor_world";
    return err;
  }
  return fn(sketch, plane);
}

void souxmar_sketch_free(souxmar_sketch_t* sketch) {
  typedef void (*fn_t)(souxmar_sketch_t* sketch);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_free");
  }
  if (fn) fn(sketch);
}

souxmar_sketch_t* souxmar_sketch_new(void) {
  typedef souxmar_sketch_t* (*fn_t)(void);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_new");
  }
  if (!fn) { souxmar_sketch_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn();
}

size_t souxmar_sketch_num_constraints(const souxmar_sketch_t* sketch) {
  typedef size_t (*fn_t)(const souxmar_sketch_t* sketch);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_num_constraints");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch);
}

size_t souxmar_sketch_num_primitives(const souxmar_sketch_t* sketch) {
  typedef size_t (*fn_t)(const souxmar_sketch_t* sketch);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_num_primitives");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(sketch);
}

souxmar_status_t souxmar_sketch_point_position(const souxmar_sketch_t* sketch, uint32_t point_id, double* out_u, double* out_v) {
  typedef souxmar_status_t (*fn_t)(const souxmar_sketch_t* sketch, uint32_t point_id, double* out_u, double* out_v);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_point_position");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_sketch_point_position";
    return err;
  }
  return fn(sketch, point_id, out_u, out_v);
}

souxmar_status_t souxmar_sketch_solve(souxmar_sketch_t* sketch) {
  typedef souxmar_status_t (*fn_t)(souxmar_sketch_t* sketch);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_sketch_solve");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_sketch_solve";
    return err;
  }
  return fn(sketch);
}

souxmar_status_t souxmar_surface_stream_bounds(const souxmar_surface_stream_t* s, double out_min[3], double out_max[3]) {
  typedef souxmar_status_t (*fn_t)(const souxmar_surface_stream_t* s, double out_min[3], double out_max[3]);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_bounds");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_surface_stream_bounds";
    return err;
  }
  return fn(s, out_min, out_max);
}

void souxmar_surface_stream_close(souxmar_surface_stream_t* stream) {
  typedef void (*fn_t)(souxmar_surface_stream_t* stream);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_close");
  }
  if (fn) fn(stream);
}

souxmar_status_t souxmar_surface_stream_face_ids(const souxmar_surface_stream_t* s, uint32_t* out, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_surface_stream_t* s, uint32_t* out, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_face_ids");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_surface_stream_face_ids";
    return err;
  }
  return fn(s, out, out_capacity);
}

souxmar_status_t souxmar_surface_stream_indices(const souxmar_surface_stream_t* s, uint32_t* out, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_surface_stream_t* s, uint32_t* out, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_indices");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_surface_stream_indices";
    return err;
  }
  return fn(s, out, out_capacity);
}

souxmar_status_t souxmar_surface_stream_normals(const souxmar_surface_stream_t* s, float* out, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_surface_stream_t* s, float* out, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_normals");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_surface_stream_normals";
    return err;
  }
  return fn(s, out, out_capacity);
}

souxmar_surface_stream_t* souxmar_surface_stream_open(const souxmar_mesh_t* mesh) {
  typedef souxmar_surface_stream_t* (*fn_t)(const souxmar_mesh_t* mesh);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_open");
  }
  if (!fn) { souxmar_surface_stream_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(mesh);
}

souxmar_status_t souxmar_surface_stream_positions(const souxmar_surface_stream_t* s, float* out, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_surface_stream_t* s, float* out, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_positions");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_surface_stream_positions";
    return err;
  }
  return fn(s, out, out_capacity);
}

size_t souxmar_surface_stream_triangle_count(const souxmar_surface_stream_t* s) {
  typedef size_t (*fn_t)(const souxmar_surface_stream_t* s);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_triangle_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(s);
}

size_t souxmar_surface_stream_vertex_count(const souxmar_surface_stream_t* s) {
  typedef size_t (*fn_t)(const souxmar_surface_stream_t* s);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_vertex_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(s);
}

souxmar_status_t souxmar_surface_stream_vertex_ids(const souxmar_surface_stream_t* s, uint64_t* out, size_t out_capacity) {
  typedef souxmar_status_t (*fn_t)(const souxmar_surface_stream_t* s, uint64_t* out, size_t out_capacity);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_surface_stream_vertex_ids");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_surface_stream_vertex_ids";
    return err;
  }
  return fn(s, out, out_capacity);
}

souxmar_status_t souxmar_timeseries_cache_preload(souxmar_timeseries_t* series, size_t start_frame, size_t count) {
  typedef souxmar_status_t (*fn_t)(souxmar_timeseries_t* series, size_t start_frame, size_t count);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_cache_preload");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_timeseries_cache_preload";
    return err;
  }
  return fn(series, start_frame, count);
}

souxmar_status_t souxmar_timeseries_cache_window(souxmar_timeseries_t* series, size_t window_size) {
  typedef souxmar_status_t (*fn_t)(souxmar_timeseries_t* series, size_t window_size);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_cache_window");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_timeseries_cache_window";
    return err;
  }
  return fn(series, window_size);
}

void souxmar_timeseries_close(souxmar_timeseries_t* series) {
  typedef void (*fn_t)(souxmar_timeseries_t* series);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_close");
  }
  if (fn) fn(series);
}

size_t souxmar_timeseries_field_count(const souxmar_timeseries_t* series) {
  typedef size_t (*fn_t)(const souxmar_timeseries_t* series);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_field_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(series);
}

const char* souxmar_timeseries_field_name(const souxmar_timeseries_t* series, size_t field_index) {
  typedef const char* (*fn_t)(const souxmar_timeseries_t* series, size_t field_index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_field_name");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(series, field_index);
}

const souxmar_field_t* souxmar_timeseries_frame(souxmar_timeseries_t* series, size_t frame_index, const char* field_name) {
  typedef const souxmar_field_t* (*fn_t)(souxmar_timeseries_t* series, size_t frame_index, const char* field_name);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_frame");
  }
  if (!fn) { const souxmar_field_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(series, frame_index, field_name);
}

size_t souxmar_timeseries_frame_count(const souxmar_timeseries_t* series) {
  typedef size_t (*fn_t)(const souxmar_timeseries_t* series);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_frame_count");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(series);
}

souxmar_timeseries_t* souxmar_timeseries_open(const char* path) {
  typedef souxmar_timeseries_t* (*fn_t)(const char* path);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_open");
  }
  if (!fn) { souxmar_timeseries_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(path);
}

souxmar_status_t souxmar_timeseries_time(const souxmar_timeseries_t* series, size_t frame_index, double* out_time) {
  typedef souxmar_status_t (*fn_t)(const souxmar_timeseries_t* series, size_t frame_index, double* out_time);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_timeseries_time");
  }
  if (!fn) {
    souxmar_status_t err;
    err.code = SOUXMAR_E_INTERNAL;
    err.message = "souxmar host ABI symbol not found in the loading executable";
    err.detail = "souxmar_timeseries_time";
    return err;
  }
  return fn(series, frame_index, out_time);
}

int souxmar_value_as_bool(const souxmar_value_t* value) {
  typedef int (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_as_bool");
  }
  if (!fn) { int zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

double souxmar_value_as_number(const souxmar_value_t* value) {
  typedef double (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_as_number");
  }
  if (!fn) { double zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

const char* souxmar_value_as_stage(const souxmar_value_t* value) {
  typedef const char* (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_as_stage");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

const char* souxmar_value_as_string(const souxmar_value_t* value) {
  typedef const char* (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_as_string");
  }
  if (!fn) { const char* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

uint8_t souxmar_value_kind(const souxmar_value_t* value) {
  typedef uint8_t (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_kind");
  }
  if (!fn) { uint8_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

const souxmar_value_t* souxmar_value_list_at(const souxmar_value_t* value, size_t index) {
  typedef const souxmar_value_t* (*fn_t)(const souxmar_value_t* value, size_t index);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_list_at");
  }
  if (!fn) { const souxmar_value_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value, index);
}

size_t souxmar_value_list_size(const souxmar_value_t* value) {
  typedef size_t (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_list_size");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

const souxmar_value_t* souxmar_value_map_get(const souxmar_value_t* value, const char* key) {
  typedef const souxmar_value_t* (*fn_t)(const souxmar_value_t* value, const char* key);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_map_get");
  }
  if (!fn) { const souxmar_value_t* zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value, key);
}

size_t souxmar_value_map_size(const souxmar_value_t* value) {
  typedef size_t (*fn_t)(const souxmar_value_t* value);
  static fn_t fn = NULL;
  if (fn == NULL) {
    fn = (fn_t)(void*)souxmar_shim_lookup("souxmar_value_map_size");
  }
  if (!fn) { size_t zero; memset(&zero, 0, sizeof zero); return zero; }
  return fn(value);
}

#endif /* _WIN32 */
